name: Linting-Precommit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre_job:
    name: Path match check
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          paths_ignore: '["**.po", "**.json"]'

  linting:
    name: All file linting
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies for web-server
        run: yarn install
        working-directory: web-server

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies for cli
        run: yarn install
        working-directory: cli

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1
